{
 "title": "IoT Mission Control",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Simulated Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "simulator_active_devices", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(simulator_messages_published_total[1m])",
     "legendFormat": "Telemetry Output (Msg/s)"
    },
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "API Traffic (Req/s)" }
   ]
  },
  {
   "title": "Avg Simulation Step Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(simulator_tick_duration_seconds_sum[1m]) / rate(simulator_tick_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}