persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Allow anonymous helper
listener 1883
allow_anonymous true

listener 9001
protocol websockets

# =================================================================
# RabbitMQ Bridge Configuration
# =================================================================
connection rabbitmq-bridge
address rabbitmq:1883
topic # out 0
topic # in 0
remote_username guest
remote_password guest
try_private false
notifications false
bridge_protocol_version mqttv311
