server {
    listen 80;
    server_name localhost;

    # DNS Resolver for Docker internal network
    resolver 127.0.0.11 valid=5s;

    # Frontend Dashboard
    location / {
        set $upstream_frontend frontend:80;
        proxy_pass http://$upstream_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Auth Microservice
    location /auth/ {
        set $upstream_auth backend:8000;
        rewrite ^/auth/(.*) /users/$1 break;
        proxy_pass http://$upstream_auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Device Management Microservice
    location /devices/ {
        set $upstream_device device-management:8001;
        rewrite ^/devices/(.*) /devices/$1 break;
        proxy_pass http://$upstream_device;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Monitoring Microservice (Telemetry API)
    location /monitor/ {
        set $upstream_monitor monitoring:8002;
        rewrite ^/monitor/(.*) /monitoring/$1 break;
        proxy_pass http://$upstream_monitor;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Socket.IO (Crucial for Real-time Charts)
    location /socket.io/ {
        set $upstream_socket monitoring:8002;
        proxy_pass http://$upstream_socket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
